---
apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
  namespace: hometask
spec:
  containers:
  - name: mycontainer
    image: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysqlsecret
            key: password
