---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-set
  namespace: hometask
spec:
  selector:
    matchLabels:
      app: article
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: article  
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: dbname
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: dbuser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: dbpass
        volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi